apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speaker-model-cache
  namespace: speaker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard 